""" Lambda Calculus (https://realpython.com/python-lambda/)
Lambda expressions in Python and other programming languages have their roots in 
lambda calculus, a model of computation invented by Alonzo Church. """

""" Lambda calculus can encode any computation. It is Turing complete, but contrary
to the concept of a Turing machine, it is pure and does not keep any state. """

""" The imperative style consists of programming with statements, driving the flow 
of the program step by step with detailed instructions. This approach promotes 
mutation and requires managing state. """

""" The separation in both families presents some nuances, as some functional 
languages incorporate imperative features, like OCaml, while functional features 
have been permeating the imperative family of languages in particular with the 
introduction of lambda functions in Java, or Python.

Python is not inherently a functional language, but it adopted some functional 
concepts early on. In January 1994, map(), filter(), reduce(), and the lambda 
operator were added to the language. """

# A lambda expression has three parts: keyword (lambda), a bound variable 
# (as argument) and a body (instructions).
lambda x: x # identity function

# You can apply the function above to an argument by surrounding the function 
# and its argument with parentheses:
(lambda x: x*x)(7)

# Because a lambda function is an expression, it can be named:
sqrt_it = lambda x: x*x
print(f"8 au carré = {sqrt_it(8)}")

# Multi-argument functions (functions that take more than one argument) are 
# expressed in Python lambdas by listing arguments and separating them with 
# a comma (,) but without surrounding them with parentheses:
fullname = lambda first, last: f"Full name: {first.title()} {last.title()}"
print("Full Name:", fullname('Bill', 'Mick'))

""" Anonymous Functions """
""" Taken literally, an anonymous function is a function without a name. In Python, 
an anonymous function is created with the lambda keyword. More loosely, it may or 
not be assigned a name. """

# lambda x, y: x + y
# Other than providing you with the feedback that Python is perfectly fine with this 
# form, it doesn’t lead to any practical use. You could invoke the function in the 
# Python interpreter:
# _(1, 2)
""" The example commented above is taking advantage of the interactive interpreter-only feature provided via the underscore (_)
https://dbader.org/blog/meaning-of-underscores-in-python """

# Another pattern used in other languages like JavaScript is to immediately execute 
# a Python lambda function. This is known as an Immediately Invoked Function 
# Expression (IIFE, pronounce “iffy”). Here’s an example:
(lambda x, y: x + y) (7, 8)
""" Python does not encourage using immediately invoked lambda expressions. It 
simply results from a lambda expression being callable, unlike the body of a 
normal function. """

""" Lambda functions are frequently used with higher-order functions, which take one 
or more functions as arguments or return one or more functions.
A lambda function can be a higher-order function by taking a function (normal or 
lambda) as an argument like in the following contrived example: """
high_ord_func = lambda x, func: x + func(x)
print(f"HOF (sqrt): {high_ord_func(2, lambda x: x * x)}")
print(f"HOF (add): {high_ord_func(2, lambda x: x + 3)}")

""" Python exposes higher-order functions as built-in functions or in the standard 
library. Examples include map(), filter(), functools.reduce(), as well as key 
functions like sort(), sorted(), min(), and max(). """

""" Lambda and Regular Functions """
""" What fundamentally distinguishes a lambda function bound to a variable from a 
regular function with a single return line: under the surface, almost nothing.
The dis module exposes functions to analyze Python bytecode generated by the Python 
compiler: """
import dis
print("LAMBDA ###########################")
add = lambda x, y: x + y
print(f"Type of add: {type(add)}")
dis.dis(add)
print(f"ADD: {add}")

print("Regular FUNCTION ###########################")
def add_f(x, y): return x + y
print(f"Type of add (reg): {type(add_f)}")
dis.dis(add_f)
print(f"ADD: {add_f}")

""" Traceback
You saw in the previous section that, in the context of the lambda function, 
Python did not provide the name of the function, but only <lambda>. This can be 
a limitation to consider when an exception occurs, and a traceback shows only 
<lambda>. """

""" Syntax
As you saw in the previous sections, a lambda form presents syntactic distinctions 
from a normal function. In particular, a lambda function has the following 
characteristics:
It can only contain expressions and can't include statements in its body.
It is written as a single line of execution.
It does not support type annotations.
It can be immediately invoked (IIFE). """

""" No Statements
A lambda function can't contain any statements. In a lambda function, 
statements like return, pass, assert, or raise will raise a SyntaxError 
exception. """

""" Single Expression
In contrast to a normal function, a Python lambda function is a single expression. 
Although, in the body of a lambda, you can spread the expression over several lines 
using parentheses or a multiline string, it remains a single expression. """

""" Type Annotations
If you've started adopting type hinting, which is now available in Python, then 
you have another good reason to prefer normal functions over Python lambda 
functions. """

""" IIFE
Immediately Invoked Function Execution. 
Outside of the Python interpreter, this feature is probably not used in practice. 
It's a direct consequence of a lambda function being callable as it is defined. 
For example, this allows you to pass the definition of a Python lambda expression 
to a higher-order function like map(), filter(), or functools.reduce(), or to a 
key function. """